#!/bin/bash

if [ $# -eq 0 ]
then 
    echo "Usage: phone searchfor [...searchfor]"
    echo "(You didn't tell me what you want to search for.)"
else
  
    arguments=$1
    for argument in $@
    do 
         arguments="${arguments}|${argument}"
    done
    
        
     egrep -i "${arguments}" data |awk -f display.awk
fi
